#!/bin/sh
### BEGIN INIT INFO
# Provides:          autonfs
# Required-Start:    $network $named $portmap $remote_fs
# Required-Stop:     $network $named $portmap $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start / Stop / Restart AutoNFS
# Description:       starts, stops or restarts the autonfs script which handles the nfs mounts
### END INIT INFO
# Author: Martin Seener <martin@seener>

# Actions
case "$1" in
	start)
		# Check for a .pid file, otherwise run that sh..cript
		echo -n "Starting AutoNFS: "
		if [ -f "/var/run/autonfs.pid" ]; then
			# .pid exists. Now we check if the process is dead
			/bin/ps aux | grep "`cat /var/run/autonfs.pid`" | grep -v grep > /dev/null 2>&1
			if [ $? -eq 0 ]; then
				# Process is running… Aborting.
				echo "AutoNFS is still running. Aborting."
				exit 0
			else
				# Process is dead… Aborting.
				echo "/var/run/autonfs.pid exists. Process not running. Aborting."
				exit 1
			fi
		else
			# No .pid - we`re starting AutoNFS.
			/bin/bash /usr/local/bin/autonfs.sh &
			echo "done."
			exit 0
		fi
		;;
	stop)
		# Stopping AutoNFS if its running
		echo -n "Stopping AutoNFS: "
		if [ -f "/var/run/autonfs.pid" ]; then
			# .pid is in place. checking if process is there
			/bin/ps aux | grep "`cat /var/run/autonfs.pid`" | grep -v grep > /dev/null 2>&1
			if [ $? -eq 0 ]; then
				# Process is there too. Let us stop it
				kill -9 `cat /var/run/autonfs.pid`
				rm -f /var/run/autonfs.pid
				echo "done."
				exit 0
			else
				# No Process found
				echo "Nothing to stop. Please delete old /var/run/autonfs.pid."
				exit 1
			fi
		else
			# No .pid found. Nothing to stop
			echo "Nothing to stop."
			exit 3
		fi
		;;
	restart)
		# Restarting AutoNFS
		echo -n "Restarting AutoNFS: ..."
		if [ -f "/var/run/autonfs.pid" ]; then
			# .pid is in place. checking if process is there
			/bin/ps aux | grep "`cat /var/run/autonfs.pid`" | grep -v grep > /dev/null 2>&1
			if [ $? -eq 0 ]; then
				# Process is there too. Let us stop it
				kill -9 `cat /var/run/autonfs.pid`
				rm -f /var/run/autonfs.pid
				echo -n "stopped ..."
				/bin/bash /usr/local/bin/autonfs.sh &
				echo "started."
				exit 0
			else
				# No Process found
				echo "Nothing to restart. Please delete old /var/run/autonfs.pid."
				exit 1
			fi
		else
			# No .pid found. Starting AutoNFS
			echo -n "Nothing to stop. Starting AutoNFS: "
			/bin/bash /usr/local/bin/autonfs.sh &
			echo "started."
			exit 0
		fi
		;;
	status)
		# Getting the status of AutoNFS
		echo -n "AutoNFS is "
		if [ -f "/var/run/autonfs.pid" ]; then
			# .pid is in place. checking if process is there
			/bin/ps aux | grep "`cat /var/run/autonfs.pid`" | grep -v grep > /dev/null 2>&1
			if [ $? -eq 0 ]; then
				echo "running. PID File in place."
				exit 0
			else
				echo "not running. PID File in place."
				exit 1
			fi
		else
			echo "not running."
			exit 3
		fi
		;;
esac
# Close Script
exit 0
